# Generated by Django 3.2.10 on 2022-01-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0017_chartbuilderchart"),
    ]

    operations = [
        migrations.AddField(
            model_name="chartbuilderchart",
            name="chart_config",
            field=models.JSONField(null=True),
        ),
    ]
