# Generated by Django 3.2.10 on 2022-01-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0018_chartbuilderchart_chart_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartbuilderchart',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chartbuilderchart',
            name='title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
